#!/usr/bin/env python3
"""Compare piawka vs pixy per-gene Fst percentile ranks on the real North/South
A. lyrata dataset, for two gene sets: (1) genes overlapping GWAS SNPs from the
supplementary table, (2) genes annotated with GO:2000028 (regulation of
photoperiodism, flowering).

Inputs (results/staging/real/, pre-staged, not regenerated by this script):
  genes.bed                                  gene intervals used as the --bed/--bed_file input
  northsouth_piawka.bed                      piawka --stats fst output
  northsouth_pixy_fst.txt                    pixy --stats fst output
  supplementary_data_4_Lyrata_GWAS_SNPs.tsv  GWAS hits with Gene_lyrata/Gene_thaliana/Common_Gene_Name
  go2000028_athaliana_genes.tsv              A. thaliana genes for GO:2000028 (scripts/fetch_go2000028_athaliana.sh)
  Phytozome/.../Alyrata_384_v2.1.P14.annotation_info.txt.gz
      official JGI annotation_info file, providing the locusName (AL1G...) <->
      Best-hit-arabi-name (AT...) crosswalk used to bridge (2) to A. lyrata gene IDs.
      NOTE: positional overlap against Ensembl Plants' independently-called
      A. lyrata gene models was tried first and rejected -- validated against
      known Gene_lyrata/Gene_thaliana pairs from the supplementary table, it
      placed the same gene 64-146 kb apart depending on the locus, i.e. no
      usable coordinate correspondence. Only the ID-based crosswalk is used.

Outputs (results/tables/):
  northsouth_fst_ranks_gwas_snp_genes.tsv
  northsouth_fst_ranks_go2000028_genes.tsv

Rank 1 = highest Fst (most differentiated) in that tool's genome-wide
distribution; percentile = 100 * (1 - (rank-1)/(N-1)), so 100 = most
differentiated, 0 = least. Ranks/percentiles are computed over the
intersection of gene loci with a defined (non-NA) Fst value in *both* tools,
so the two tools' percentiles are directly comparable gene-for-gene.
"""
import csv
import gzip
import pathlib
import statistics

ROOT = pathlib.Path(__file__).resolve().parents[1]
STAGE = ROOT / "results" / "staging" / "real"
TABLES = ROOT / "results" / "tables"

GENES_BED = STAGE / "genes.bed"
PIAWKA_BED = STAGE / "northsouth_piawka.bed"
PIXY_TXT = STAGE / "northsouth_pixy_fst.txt"
SUPPLEMENTARY = STAGE / "supplementary_data_4_Lyrata_GWAS_SNPs.tsv"
GO_ATHALIANA = STAGE / "go2000028_athaliana_genes.tsv"
PHYTOZOME_ANNOTATION = (
    STAGE
    / "Phytozome"
    / "PhytozomeV14"
    / "Alyrata"
    / "v2.1"
    / "annotation"
    / "Alyrata_384_v2.1.P14.annotation_info.txt.gz"
)
GO_TERM = "GO:2000028"


def read_tsv(path, **kwargs):
    with path.open() as fh:
        return list(csv.DictReader(fh, delimiter="\t", **kwargs))


# genes.bed gene names are NOT unique: ~420 names (mostly apparent paralogs)
# label more than one interval. Rank tables are therefore keyed throughout by
# the full interval (chrom, start, end, locus), never by locus name alone --
# collapsing to locus name would silently keep only one interval's Fst per
# duplicated gene name.


def load_genes_bed():
    """(chrom, start, end) -> locus name, for locus name lookup by interval."""
    by_interval = {}
    with GENES_BED.open() as fh:
        for line in fh:
            chrom, start, end, name = line.rstrip("\n").split("\t")[:4]
            by_interval[(chrom, start, end)] = name
    return by_interval


def load_piawka():
    """(chrom, start, end, locus) -> fst (float), excluding unannotated (\"-\") intervals."""
    fst_by_interval = {}
    with PIAWKA_BED.open() as fh:
        header = fh.readline().lstrip("#").rstrip("\n").split("\t")
        reader = csv.DictReader(fh, fieldnames=header, delimiter="\t")
        for row in reader:
            locus = row["locus"]
            if locus == "-":
                continue
            key = (row["chr"], row["start"], row["end"], locus)
            fst_by_interval[key] = float(row["value"])
    return fst_by_interval


def load_pixy(genes_by_interval):
    """(chrom, start, end, locus) -> fst (float), joined to genes.bed by exact interval."""
    fst_by_interval = {}
    unmatched = 0
    for row in read_tsv(PIXY_TXT):
        if row["avg_hudson_fst"] == "NA" or row["avg_hudson_fst"] == "":
            continue
        bed_key = (row["chromosome"], row["window_pos_1"], row["window_pos_2"])
        locus = genes_by_interval.get(bed_key)
        if locus is None:
            unmatched += 1
            continue
        if locus == "-":
            continue
        key = (*bed_key, locus)
        fst_by_interval[key] = float(row["avg_hudson_fst"])
    if unmatched:
        print(f"  pixy: {unmatched} rows had no matching genes.bed interval (skipped)")
    return fst_by_interval


def rank_and_percentile(fst_by_interval):
    """interval key -> (rank, percentile), rank 1 = highest Fst."""
    ordered = sorted(fst_by_interval.items(), key=lambda kv: kv[1], reverse=True)
    n = len(ordered)
    out = {}
    for i, (key, _) in enumerate(ordered, start=1):
        percentile = 100.0 * (1 - (i - 1) / (n - 1)) if n > 1 else 100.0
        out[key] = (i, percentile)
    return out


def load_gwas_gene_set():
    """AL1G locus -> (gene_thaliana, common_name), from the supplementary GWAS table."""
    genes = {}
    for row in read_tsv(SUPPLEMENTARY):
        locus = row["Gene_lyrata"].strip()
        if not locus:
            continue
        genes.setdefault(locus, (row["Gene_thaliana"].strip(), row["Common_Gene_Name"].strip()))
    return genes


def load_go_gene_set():
    """AL1G locus -> (gene_thaliana, common_name), bridged via the Phytozome
    locusName <-> Best-hit-arabi-name crosswalk."""
    at_names = {}
    for row in read_tsv(GO_ATHALIANA):
        at_names[row["Gene stable ID"]] = row["Gene name"]

    genes = {}
    with gzip.open(PHYTOZOME_ANNOTATION, "rt") as fh:
        header = fh.readline().lstrip("#").rstrip("\n").split("\t")
        reader = csv.DictReader(fh, fieldnames=header, delimiter="\t")
        for row in reader:
            at_id = row["Best-hit-arabi-name"].strip()
            if at_id not in at_names:
                continue
            locus = row["locusName"].strip()
            common = at_names[at_id]
            if common == at_id:  # BioMart falls back to the AT id when no symbol exists
                common = ""
            genes[locus] = (at_id, common)
    return genes


def build_table(gene_set, piawka_ranks, pixy_ranks, piawka_fst, pixy_fst):
    # Group interval keys (chrom, start, end, locus) by locus name so genes
    # with more than one genomic interval (apparent paralogs in genes.bed)
    # emit one row per interval instead of an arbitrary/silent single pick.
    intervals_by_locus = {}
    for key in set(piawka_ranks) & set(pixy_ranks):
        intervals_by_locus.setdefault(key[3], []).append(key)

    rows = []
    missing = []
    for locus, (gene_thaliana, common_name) in sorted(gene_set.items()):
        keys = intervals_by_locus.get(locus)
        if not keys:
            missing.append(locus)
            continue
        for key in sorted(keys):
            _, p_pct = piawka_ranks[key]
            _, x_pct = pixy_ranks[key]
            rows.append(
                {
                    "gene_lyrata": locus,
                    "interval": f"{key[0]}:{key[1]}-{key[2]}",
                    "gene_thaliana": gene_thaliana,
                    "common_name": common_name,
                    "piawka_fst": f"{piawka_fst[key]:.6g}",
                    "piawka_percentile": f"{p_pct:.3f}",
                    "pixy_fst": f"{pixy_fst[key]:.6g}",
                    "pixy_percentile": f"{x_pct:.3f}",
                    "piawka_minus_pixy_percentile": f"{p_pct - x_pct:+.3f}",
                }
            )
    rows.sort(key=lambda r: float(r["piawka_percentile"]), reverse=True)
    return rows, missing


def wilcoxon_signed_rank(diffs):
    """Minimal paired Wilcoxon signed-rank test (two-sided normal approximation).
    Returns (W, z, p) or None if fewer than 2 non-zero differences."""
    nz = [d for d in diffs if d != 0]
    n = len(nz)
    if n < 2:
        return None
    ranked = sorted(range(n), key=lambda i: abs(nz[i]))
    ranks = [0.0] * n
    i = 0
    while i < n:
        j = i
        while j + 1 < n and abs(nz[ranked[j + 1]]) == abs(nz[ranked[i]]):
            j += 1
        avg_rank = (i + 1 + j + 1) / 2.0
        for k in range(i, j + 1):
            ranks[ranked[k]] = avg_rank
        i = j + 1
    w_plus = sum(r for r, d in zip(ranks, nz) if d > 0)
    w_minus = sum(r for r, d in zip(ranks, nz) if d < 0)
    w = min(w_plus, w_minus)
    mean_w = n * (n + 1) / 4.0
    sd_w = (n * (n + 1) * (2 * n + 1) / 24.0) ** 0.5
    z = (w - mean_w) / sd_w if sd_w > 0 else 0.0
    p = 2 * (1 - _norm_cdf(abs(z)))
    return w_plus, z, min(p, 1.0)


def _norm_cdf(x):
    return 0.5 * (1 + _erf(x / 2**0.5))


def _erf(x):
    # Abramowitz-Stegun 7.1.26 approximation, good to ~1.5e-7.
    sign = 1 if x >= 0 else -1
    x = abs(x)
    a1, a2, a3, a4, a5 = 0.254829592, -0.284496736, 1.421413741, -1.453152027, 1.061405429
    p = 0.3275911
    t = 1.0 / (1.0 + p * x)
    y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * (2.718281828459045 ** (-x * x))
    return sign * y


def summarize(name, rows):
    if not rows:
        print(f"{name}: 0 genes with defined Fst in both tools")
        return
    diffs = [float(r["piawka_minus_pixy_percentile"]) for r in rows]
    n_higher_in_piawka = sum(1 for d in diffs if d > 0)
    test = wilcoxon_signed_rank(diffs)
    print(f"{name}: n={len(rows)} genes; {n_higher_in_piawka}/{len(rows)} rank higher in piawka than pixy")
    print(f"  mean percentile diff (piawka - pixy) = {statistics.mean(diffs):+.2f}")
    if test:
        w_plus, z, p = test
        print(f"  paired Wilcoxon signed-rank: W+={w_plus:.1f}, z={z:.3f}, p={p:.4g}")


def write_tsv(path, rows, fieldnames):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fieldnames, delimiter="\t")
        w.writeheader()
        w.writerows(rows)


def main():
    genes_by_interval = load_genes_bed()
    print(f"genes.bed: {len(genes_by_interval)} intervals")

    piawka_fst = load_piawka()
    pixy_fst = load_pixy(genes_by_interval)
    print(f"piawka: {len(piawka_fst)} intervals with defined Fst")
    print(f"pixy:   {len(pixy_fst)} intervals with defined Fst")

    common_intervals = set(piawka_fst) & set(pixy_fst)
    print(f"intersection (defined in both tools): {len(common_intervals)} intervals")
    piawka_ranks = rank_and_percentile({k: v for k, v in piawka_fst.items() if k in common_intervals})
    pixy_ranks = rank_and_percentile({k: v for k, v in pixy_fst.items() if k in common_intervals})

    fieldnames = [
        "gene_lyrata",
        "interval",
        "gene_thaliana",
        "common_name",
        "piawka_fst",
        "piawka_percentile",
        "pixy_fst",
        "pixy_percentile",
        "piawka_minus_pixy_percentile",
    ]

    gwas_genes = load_gwas_gene_set()
    gwas_rows, gwas_missing = build_table(gwas_genes, piawka_ranks, pixy_ranks, piawka_fst, pixy_fst)
    out1 = TABLES / "northsouth_fst_ranks_gwas_snp_genes.tsv"
    write_tsv(out1, gwas_rows, fieldnames)
    print(f"\nWrote {out1} ({len(gwas_rows)} genes; {len(gwas_missing)} skipped, no Fst in both tools: {gwas_missing})")
    summarize("GWAS SNP genes", gwas_rows)

    go_genes = load_go_gene_set()
    go_rows, go_missing = build_table(go_genes, piawka_ranks, pixy_ranks, piawka_fst, pixy_fst)
    out2 = TABLES / "northsouth_fst_ranks_go2000028_genes.tsv"
    write_tsv(out2, go_rows, fieldnames)
    print(f"\nWrote {out2} ({len(go_rows)} genes; {len(go_missing)} skipped, no Fst in both tools: {go_missing})")
    summarize(f"{GO_TERM} genes", go_rows)


if __name__ == "__main__":
    main()
